Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "master", primary: true do |master|
    master.vm.network "private_network", ip: "192.168.33.9"
    master.vm.hostname="KubMaster"
    master.vm.provider "virtualbox" do |vb|
       vb.name = "KubMaster"
       vb.memory = "3072"
       vb.cpus   = "2"
    end
  end

  (1..2).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname="KubeNode#{i}"
      node.vm.network "private_network", ip: "192.168.33.1#{i}"
      node.vm.provider "virtualbox" do |node|
        node.name = "KubeNode#{i}"
      end
    end
  end
end
